//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Day_23MVC.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class User_Tbl
    {
        public int Id { get; set; }
        [Required(ErrorMessage ="Name is required field")]
        public string Name { get; set; }
        [Required(ErrorMessage = "Age is required field")]
        public Nullable<int> Age { get; set; }
        [Required(ErrorMessage = "Gender is required field")]
        public string Gender { get; set; }
        [Required(ErrorMessage = "Address is required field")]
        public string Address { get; set; }
    }
}
